In [2]:
#import numpy package (numpy is imported as np)
import numpy as np

In [3]:
#create numpy array from list
a = [1,2,3,4] #define an usual python list first
a1 = np.array()#then create numpy array from that list
a1


TypeError: array() missing required argument 'object' (pos 1)

In [3]:
#create another numpy array from list
b = [5,6,7,8]
b1 = np.array()
b1

array([5, 6, 7, 8])

In [4]:
#add two numpy arrays
a1+b1

array([ 6,  8, 10, 12])

In [5]:
#now add two usual python lists defined above
a+b


[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
#carefully check the difference between numpy array and list above.Mathematical functions are applied on entire numpy array 
#without having to write loops.


In [6]:
#check shape of array a1
a1.shape

(4,)

In [7]:
#check size of array a1
a1.size

4

In [8]:
#check data type of array a1
a1.dtype

dtype('int32')

In [9]:
#check dimension of array a1
a1.ndim

1

In [ ]:
#other methods to create numpy arrays

In [10]:
#using range function
d1 = np.arange(15) #this will create a one-dimensional array of items from 0 -14
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
#you can reshape and create a two-dimensional array from the d1 array above
d1.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
#you can specify the first number of the range- here you have mentioned startig point as 2. 
#So the array starts with number '2'
np.arange(2,12).reshape(2,5)

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [13]:
#few other rmethods to create numpy arrays with certain values
#with 0's only
e1 = np.zeros(10)
e1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#with 1's only
f1=np.ones(10)
f1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
#if you want to change an array from one dtype to other
#change e1 array above from float to integer
e1.astype(np.int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
#array arithmetic

In [17]:
#multiply one array with another - each element of the first array is multiplied by the corresponding element in the second array
#Note: two arrays should be of same shape for multplication
a1*b1


array([ 5, 12, 21, 32])

In [18]:
#multiply an array with a number
a1*.05

array([0.05, 0.1 , 0.15, 0.2 ])

In [19]:
#addition
a1+b1

array([ 6,  8, 10, 12])

In [20]:
#addition by a number
a1+5


array([6, 7, 8, 9])

In [21]:
#substraction
a1-b1

array([-4, -4, -4, -4])

In [22]:
#substraction by a number
a1-5

array([-4, -3, -2, -1])

In [23]:
#division
1/a1

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [24]:
#comparison
a1>b1 #here all the elements of b1 are greater than the elements of a1- so the answer is all false

array([False, False, False, False])

In [ ]:
#Slicing of array

In [25]:
#first, we are creating a one dimentional numpy array from a list
g1 = np.array([0,2,3,10,5,7])
g1

array([ 0,  2,  3, 10,  5,  7])

In [39]:
#slicing of one dimensional numpy array works same way as a list  
#print the numbers from 2,3,10,5 from the above array g1 with the help of index 
g1[1:5]

array([ 2,  3, 10,  5])

In [26]:
#change one element in one dimensional array
g1[4]=6 #4th indexed position element is chnaged from 5 to 6  
g1

array([ 0,  2,  3, 10,  6,  7])

In [27]:
#now we are creating a two dimensional array 
g2 = np.arange(9).reshape(3,3)
g2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
g2.shape

(3, 3)

In [43]:
#slicing of two dimensional array is based on rows and columns
#slice the last two elements of the first and second row
#the index range before ',' defines rows and after ',' defines column in the below code


array([[1, 2],
       [4, 5]])

In [29]:
#slice only the third row
#Third row is in the 2nd inexed positon and and you need all the elements of the third row, so the code is 


array([6, 7, 8])

In [ ]:
#For more examples of two-dimensional array slicing, refer slide 11

In [36]:
#change one element in two dimensional array
 # chnage the second element of second row (4 changed to 10)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 6, 6]])

In [30]:
#create an array of random numbers (this will generate randome numbers >=2 and <10)
np.random.randint(2,10, size=(2,4))

array([[3, 2, 9, 9],
       [7, 8, 5, 9]])

In [ ]:
#some statistical methods

In [31]:
#sum of aLL the numbers of an array
np.sum(g2)

36

In [32]:
#average of all numbers of an array 
np.mean(g2)

4.0

In [33]:
#minimum of all the numbers of an array
np.min(g2)

0

In [34]:
#maximum of all the numbers of an array
np.max(g2)

8

In [35]:
#square of all numbers of an array
np.square(g2)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)